# Generated by Django 3.0.7 on 2020-09-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
    ]
